package states

const (
	PREPARATION_GAME_STATE = iota
	INITIALIZATION_GAME_STATE
	PLAYING_GAME_STATE
	TERMINATED_GAME_STATE

	FLIP_DICE_ROUND
	MOVEMENT_ROUND
	CALL_ROUND
	DECLARATION_ROUND

	SELECTION_CALL_STATE
	CALL_OBJECTS_CALL_STATE
)
